### ISSUE TITLE
Can you provide a fully working standalone React demo?

### ISSUE THREAD

**Issue by hsluoyz** [nbudin/react-blockly#14]
https://github.com/nbudin/react-blockly/blob/master/public/index.html this is NOT react.

**Comment by realies** [comment]
Would be great to have a minimal example available. Trying to replicate the demo react app in a separate project without any success so far. @nbudin, would this be possible?

**Comment by anovis** [comment]
having similar issue.

**Comment by OriAmir** [comment]
anything new about that? maybe someone has some demo that works?

**Comment by nbudin** [comment]
Hey folks, if you look in src/dev-index.jsx in this repository, you will see a fully working React demo.  If you want to run it, checkout the repo locally and run `yarn install` and `yarn run start`.

If someone would like to provide a separate repo with an app, I would be happy to link there.  I don't have a lot of time to work on this package myself anymore, and if any of you would be interested in becoming a maintainer I would be more than happy to give you rights on here or transfer the project, depending on your preferences.

**Comment by OriAmir** [comment]
@nbudin thanks for the answer!
If you don't have time to work on this library anymore it's said that this library not gone a be update soon?
I read that a new major release of `blockly` is upcoming in 2 weeks so the question if someone has gone to adjust that to this library?

**Comment by nbudin** [comment]
@OriAmir I've been releasing updates to this library when new versions of Blockly come out, since that has been relatively little effort to do, and I intend to continue doing so unless someone else steps up.  I've also been reviewing PRs and cutting releases when those come up.  However, I don't have time to provide additional feature work or documentation updates myself.

**Comment by rachel-fenichel** [comment]
@nbudin do you have an estimate on how much work (hours/week or hours/release) it takes to maintain this project?

**Comment by nbudin** [comment]
@rachel-fenichel It varies.  The 4.0.0 release took a good bit of time (maybe 10-20 hours), since it required splitting the project away from its previous organization, renaming the package, doing a bunch of associated work on the build infrastructure, etc.

The releases since then have been more like 1-2 hours each.  My usual process is to code review the PR, try it out myself using the built-in testbed app you get with `yarn run start`, and do any QA necessary.  For the recent ones, the issues I've found have been either none, or minimal enough that I was able to easily fix them before releasing.

If you're potentially interested in becoming a maintainer, I'd be happy to chat more!  You can email me at natbudin@gmail.com and I'm also happy to chat via phone or video call if that's your preference.  (I'm currently working through some repetitive stress injury stuff and so I might be faster/more responsive via non-text communication.)

**Comment by nbudin** [comment]
FernandoVazZ made an example project, which is linked from the README now: https://github.com/FernandoVazZ/reactblockly-customblocks/
