### ISSUE TITLE
Failed to parse source map

### ISSUE THREAD

**Issue by Chambana** [nbudin/react-blockly#87]
I just installed the react-blockly module via npm (`npm install react-blockly`).  By simply importing BlocklyWorkspace (`import { BlocklyWorkspace } from 'react-blockly'`) I get over 15 warnings and the example code fails to display anything.  Here is an example of the warnings:

```
WARNING in ./node_modules/blockly/blockly_compressed.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/blah/react/live-robot-control/node_modules/blockly/src/com/google/javascript/jscomp/js/es6/array/flat.js' file: 
Error: ENOENT: no such file or directory, open '/home/blah/react/live-robot-control/node_modules/blockly/src/com/google/javascript/jscomp/js/es6/array/flat.js'

WARNING in ./node_modules/blockly/blockly_compressed.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/blah/react/live-robot-control/node_modules/blockly/src/com/google/javascript/jscomp/js/es6/array/values.js' file: 
Error: ENOENT: no such file or directory, open '/home/blah/react/live-robot-control/node_modules/blockly/src/com/google/javascript/jscomp/js/es6/array/values.js'

WARNING in ./node_modules/blockly/blockly_compressed.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/blah/react/live-robot-control/node_modules/blockly/src/com/google/javascript/jscomp/js/es6/globalthis.js' file: 
Error: ENOENT: no such file or directory, open '/home/blah/react/live-robot-control/node_modules/blockly/src/com/google/javascript/jscomp/js/es6/globalthis.js'
```

and here are the react and react-blockly entries in my package.json
```
    "react": "^18.2.0",
    "react-blockly": "^7.1.0",
```

I'd really like to use this module, any suggestions?

**Comment by Chambana** [comment]
This is reproducible on my machine by creating a default react-app, installing react-blockly via npm, and then adding the example react-blockly code.  No blockly component appears:
```

import logo from './logo.svg';
import './App.css';
import { BlocklyWorkspace } from 'react-blockly';
import { useState } from 'react';


var theToolbox = {
    "kind": "flyoutToolbox",
    "contents": [
      {
        "kind": "block",
        "type": "controls_if"
      },
      {
        "kind": "block",
        "type": "controls_whileUntil"
      }
    ]
  };

function MyBlocklyEditor() {
  const [xml, setXml] = useState();

  return (
    <BlocklyWorkspace
      className="width-100" // you can use whatever classes are appropriate for your app's CSS
      toolboxConfiguration={theToolbox} // this must be a JSON toolbox definition
      initialXml={xml}
      onXmlChange={setXml}
    />
  )
}

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
        <div>
          MyBlockyEditor should be below:
          <MyBlocklyEditor/>
          and it's not
      </div>
      </header>

    </div>

  );
}

export default App;
```
Here is the rendered output
![image](https://user-images.githubusercontent.com/14134766/221747114-77427b8a-27f1-41f7-9f62-33b024190b55.png)

**Comment by nbudin** [comment]
Hi @Chambana!  Believe it or not, in your example code, the Blockly editor is actually rendering!  It's just so small you can't see it 🙃 

I made a new create-react-app application and pasted your code in, and I saw the same thing you did.  If you inspect the HTML of the page in your developer tools, you'll see that there is actually a div on the page with class `width-100`, and a whole lot of Blockly stuff inside that, indicating that the BlocklyWorkspace component is getting rendered.  However, since the CSS class `width-100` is not actually defined anywhere in your application, it doesn't do anything, so the Blockly div is 0 pixels wide and 0 pixels tall, which is Blockly's default.

To fix it, we can add something like this in App.css:

```css
.width-100 {
  width: 1024px;
  height: 800px;
}
```

Now that that's done, you'll see a white box on the page.  Still no Blockly editor, though.  The error here is a bit more subtle, and to be honest, I'm not sure why it's not logging anything to the developer console about it, but the issue is that the way you're calling `useState()`, it sets the initial state as `undefined` (rather than an empty string), and Blockly doesn't like that.  To fix it, you can change the useState line as follows:

```js
const [xml, setXml] = useState("");
```

Once I made these changes, the Blockly editor appeared for me.  Hopefully it will for you as well.

I think the source map thing might be an issue in your local setup; I'm not sure where it's coming from but the errors don't mention react-blockly; they mention sub-dependencies of blockly itself.

**Comment by Chambana** [comment]
Great catch and thank you so much!
