### ISSUE TITLE
Enable JSON format sidelong XML

### ISSUE THREAD

**Issue by arielshulman** [nbudin/react-blockly#88]
Hey, 
Thanks for the great job.
I was wondering if there is a way to enable JSON serialization system alongside the XML one?
As [google advise](https://developers.google.com/blockly/guides/configure/web/serialization), JSON is the future of serialization.

**Comment by nbudin** [comment]
Thanks for the suggestion @arielshulman!  I agree, this is important to add.  I probably won't be able to get to it this week, but here's roughly what I'm thinking:

1. Add `initialJson` and `onJsonChange` props alongside the existing `initialXml` and `onXmlChange` props.  
2. Deprecate the XML ones in the TypeScript definitions.
3. Make a minor release (e.g. 7.2.0) with these changes.

If anyone has time to work on this this week, I'd gladly accept a PR!  Otherwise I will try to get to it as soon as I can.

**Comment by nbudin** [comment]
This is now released in 7.2.1!
